name: PyPI Deploy

on:
  push:
    tags:
    - '*'

jobs:

  # Automatically deploy releases to PyPI for each tagged commit. This
  # uses the API Token feature (https://pypi.org/help/#apitoken). After
  # obtaining an API token from PyPI, add it to your github secrets with
  # the name `pypi_password`.
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.1.5

      - name: Configure Poetry
        run: poetry config virtualenvs.in-project true

      - name: Install Package
        run: poetry install --no-interaction
          
      - name: Build
        run: poetry build
    
      - name: Publish package
        if: startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}