name: Generate Docs

on:
  push:
    branches: [ dev ]

jobs:

  docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        run: pipx install poetry
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: 'poetry'

      - name: Install Package
        if: steps.cache-primes.outputs.cache-hit != 'true' # Only run if the cache is old
        run: poetry install --no-interaction -E examples

      - name: Build Documentation
        run: poetry run invoke docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: docs/_build
