# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test CI

on:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]
    defaults:
      run:
        shell: bash

    runs-on: ${{ matrix.os }}
    timeout-minutes: 25

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-in-project: true

      - name: Cache Virtual Environment
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Package
        if: steps.cache-primes.outputs.cache-hit != 'true' # Only run if the cache is old
        run: poetry install --no-interaction -E examples

      - name: Lint
        run: poetry run invoke lint

      - name: Test Unit
        run: poetry run invoke test-unit

      - name: Test README
        run: poetry run invoke test-readme

      - name: Test Tutorials
        run: poetry run invoke test-tutorials
